# Generated by Django 4.2.17 on 2025-01-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_project_submission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'project')},
        ),
    ]
