# Generated by Django 4.2.17 on 2025-01-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.CharField(choices=[('Django', 'Django'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI')], max_length=50, null=True),
        ),
    ]
