# Generated by Django 4.2.17 on 2025-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_project_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='area_of_interest',
            field=models.CharField(choices=[('Django', 'Django'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI')], max_length=50, null=True),
        ),
    ]
