# Generated by Django 4.2.17 on 2025-01-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='user_management.subtopic'),
        ),
    ]
