# Generated by Django 4.2.17 on 2025-01-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_customuser_address_customuser_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='area_of_interest',
            field=models.CharField(choices=[('Django', 'Django'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI'), ('Laravell', 'Laravell'), ('React', 'React')], max_length=100),
        ),
    ]
