# Generated by Django 4.2.17 on 2025-01-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_alter_userprofile_area_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.CharField(choices=[('Django', 'Django'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI'), ('Laravel', 'Laravel'), ('React', 'React')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='area_of_interest',
            field=models.CharField(choices=[('Django', 'Django'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI'), ('Laravel', 'Laravel'), ('React', 'React')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area_of_interest',
            field=models.CharField(choices=[('Django', 'Django'), ('Machine Learning', 'Machine Learning'), ('AI', 'AI'), ('Laravel', 'Laravel'), ('React', 'React')], max_length=100),
        ),
    ]
