# Generated by Django 4.2.17 on 2025-01-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_alter_project_topic_alter_topic_area_of_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
