# Generated by Django 4.2.17 on 2025-01-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_userprofile_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='customuser',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
