# Generated by Django 4.2.17 on 2025-01-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
