# Generated by Django 4.2.17 on 2025-01-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
