# Generated by Django 4.2.17 on 2025-01-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('simple_layout', 'Simple Layout'), ('creative_layout', 'Creative Layout')], max_length=50, null=True),
        ),
    ]
