# Generated by Django 4.2.17 on 2025-01-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0035_blogpost_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
