# Generated by Django 4.2.17 on 2025-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0037_alter_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('simple_layout', 'Simple Layout'), ('creative_layout', 'Creative Layout'), ('professional', 'professional'), ('attractive', 'attractive')], max_length=50, null=True),
        ),
    ]
