# Generated by Django 4.2.17 on 2025-01-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0043_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
